---
# tasks file for publish-github
- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: github-wiki
  register: tempdir

- name: Clone wiki repo
  git:
    repo: git@github.com:{{ github.repo_owner }}/{{ github.repo }}.wiki.git
    dest: "{{ tempdir.path }}/{{ github.repo }}.wiki"
    version: HEAD

- name: Add conents to wiki file
  copy:
    content: "{{ generate_docs.output }}"
    dest: "{{ tempdir.path }}/{{ github.repo }}.wiki/{{ github.edit_doc }}"

# Seems like this has to use shell module due to use of chdir
- name: Publish changes to wiki
  shell: |
    chdir={{ tempdir.path }}/{{ github.repo }}.wiki
    git add {{ github.edit_doc }}
    git commit -m "{{ github.commit_message }}"
    git push
  notify: github cleanup temp
