---
# tasks file for gen-docs

- name: Register template
  set_fact:
    documentation: "{{ lookup('template', '{{ template_name }}')}}"

- name: Save markdown file
  copy:
    content: "{{ documentation }}"
    dest: "{{ path }}/{{ docname }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664
