---
# tasks file for publish-docs

- name: Check if Publishing to Github
  include_tasks: github/main.yml
  when: github is defined

- name: Check if Publishing to Gitlab
  include_tasks: gitlab/main.yml
  when: gitlab is defined

- name: Check if Publishing to Confluence
  include_tasks: confluence/main.yml
  when: confluence is defined
